### ISSUE TITLE
Puma problem

### ISSUE THREAD

**Issue by DeLaGuardo** [gitlabhq/gitlab-ci#160]
This problem fixed by removing .socket file, but after one build rise again.

```
Puma 2.0.0.b7 starting...
* Min threads: 0, max threads: 16
* Environment: production
* Listening on unix:///home/gitlab_ci/gitlab-ci/tmp/sockets/gitlab-ci.socket
/home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/1.9.1/gems/puma-2.0.0.b7/lib/puma/binder.rb:234:in `initialize': Address already in use - "/home/gitlab_ci/gitlab-ci/tmp/sockets/gitlab-ci.socket" (Errno::EADDRINUSE)
	from /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/1.9.1/gems/puma-2.0.0.b7/lib/puma/binder.rb:234:in `new'
	from /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/1.9.1/gems/puma-2.0.0.b7/lib/puma/binder.rb:234:in `add_unix_listener'
	from /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/1.9.1/gems/puma-2.0.0.b7/lib/puma/binder.rb:96:in `block in parse'
	from /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/1.9.1/gems/puma-2.0.0.b7/lib/puma/binder.rb:64:in `each'
	from /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/1.9.1/gems/puma-2.0.0.b7/lib/puma/binder.rb:64:in `parse'
	from /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/1.9.1/gems/puma-2.0.0.b7/lib/puma/cli.rb:414:in `run_single'
	from /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/1.9.1/gems/puma-2.0.0.b7/lib/puma/cli.rb:402:in `run'
	from /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/1.9.1/gems/puma-2.0.0.b7/bin/puma:10:in `<top (required)>'
	from /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/1.9.1/bin/puma:23:in `load'
	from /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/1.9.1/bin/puma:23:in `<main>'
Gitlab CI service started
```

**Comment by jvanbaarsen** [comment]
We switched to Unicorn. I'll close this issue.
