### ISSUE TITLE
Build fails if utf8 symbols present in output

### ISSUE THREAD

**Issue by kolashtov** [gitlabhq/gitlab-ci#196]
Hello. My build fails if some command's output contains non-english symbols.
For example if I run bundle exec rake db:drop, gitlab-ci output:
```
bundle exec rake db:drop
rake aborted!
U+041E from UTF-8 to US-ASCII
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/bundler/gems/rails-dbd26e92a7b9/activerecord/lib/active_record/railties/databases.rake:631:in `write'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/bundler/gems/rails-dbd26e92a7b9/activerecord/lib/active_record/railties/databases.rake:631:in `puts'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/bundler/gems/rails-dbd26e92a7b9/activerecord/lib/active_record/railties/databases.rake:631:in `rescue in drop_database_and_rescue'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/bundler/gems/rails-dbd26e92a7b9/activerecord/lib/active_record/railties/databases.rake:628:in `drop_database_and_rescue'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/bundler/gems/rails-dbd26e92a7b9/activerecord/lib/active_record/railties/databases.rake:178:in `block (3 levels) in <top (required)>'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/bundler/gems/rails-dbd26e92a7b9/activerecord/lib/active_record/railties/databases.rake:178:in `each'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/bundler/gems/rails-dbd26e92a7b9/activerecord/lib/active_record/railties/databases.rake:178:in `block (2 levels) in <top (required)>'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/home/gitlab_ci/my_site_ru/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
Tasks: TOP => db:drop
(See full trace by running task with --trace)
```

But if I run this command manually from shell I have output:
```
gitlab_ci@project ~/my_site_ru $ bundle exec rake db:drop
ЗАМЕЧАНИЕ:  база данных "my_site_test" не существует, пропускается
```

This appears not only with rake db:drop. What i'm doing wrong?

UPD: My gitlab-ci version is 2.2.0.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
