### ISSUE TITLE
Requesting page as JSON gives 500 error - Missing Template?

### ISSUE THREAD

**Issue by sammcj** [gitlabhq/gitlab-ci#489]
I'm trying to render the runners page as JSON and it causes a 500 error:

https://ci/admin/runners.json
```{"status":"500","error":"Internal Server Error"}```

```
Started PUT "/api/v1/builds/1379.json" for 127.0.0.1 at 2014-11-06 10:42:19 +1100
Started GET "/admin/runners.json" for 127.0.0.1 at 2014-11-06 10:42:19 +1100
Processing by Admin::RunnersController#index as JSON
Completed 500 Internal Server Error in 5ms

ActionView::MissingTemplate (Missing template admin/runners/index, admin/application/index, application/index with {:locale=>[:en], :formats=>[:json], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :coffee, :haml]}. Searched in:
  * "/home/gitlab_ci/gitlab-ci/app/views"
  * "/home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/1.9.1/gems/kaminari-0.15.0/app/views"
):
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_view/path_set.rb:46:in `find'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_view/lookup_context.rb:122:in `find'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_view/renderer/template_renderer.rb:35:in `determine_template'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_view/renderer/template_renderer.rb:8:in `render'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_view/renderer/renderer.rb:42:in `render_template'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_view/renderer/renderer.rb:23:in `render'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/abstract_controller/rendering.rb:127:in `_render_template'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal/streaming.rb:219:in `_render_template'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/abstract_controller/rendering.rb:120:in `render_to_body'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal/rendering.rb:33:in `render_to_body'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal/renderers.rb:26:in `render_to_body'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/abstract_controller/rendering.rb:97:in `render'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal/rendering.rb:16:in `render'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.10/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.10/lib/active_support/core_ext/benchmark.rb:12:in `ms'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  vendor/bundle/ruby/1.9.1/gems/activerecord-4.0.10/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal/instrumentation.rb:40:in `render'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/abstract_controller/base.rb:189:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.10/lib/active_support/callbacks.rb:453:in `_run__1730310369138512785__process_action__callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.10/lib/active_support/callbacks.rb:80:in `run_callbacks'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/abstract_controller/callbacks.rb:17:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.10/lib/active_support/notifications.rb:159:in `block in instrument'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.10/lib/active_support/notifications.rb:159:in `instrument'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/activerecord-4.0.10/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/abstract_controller/base.rb:136:in `process'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/abstract_controller/rendering.rb:44:in `process'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal.rb:195:in `dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_controller/metal.rb:231:in `block in action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_dispatch/routing/route_set.rb:82:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_dispatch/routing/route_set.rb:50:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_dispatch/journey/router.rb:71:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_dispatch/journey/router.rb:59:in `each'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_dispatch/journey/router.rb:59:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_dispatch/routing/route_set.rb:676:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_dispatch/middleware/flash.rb:241:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_dispatch/middleware/cookies.rb:486:in `call'
  vendor/bundle/ruby/1.9.1/gems/activerecord-4.0.10/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/1.9.1/gems/activerecord-4.0.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.10/lib/active_support/callbacks.rb:373:in `_run__4488782855680495857__call__callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.10/lib/active_support/callbacks.rb:80:in `run_callbacks'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-4.0.10/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/1.9.1/gems/railties-4.0.10/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.10/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.10/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/1.9.1/gems/railties-4.0.10/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.0.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.10/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-4.0.10/lib/rails/engine.rb:511:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-4.0.10/lib/rails/application.rb:97:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-4.0.10/lib/rails/railtie/configurable.rb:30:in `method_missing'
  vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
  vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
  vendor/bundle/ruby/1.9.1/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:572:in `process_client'
  vendor/bundle/ruby/1.9.1/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:666:in `worker_loop'
  vendor/bundle/ruby/1.9.1/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:521:in `spawn_missing_workers'
  vendor/bundle/ruby/1.9.1/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:140:in `start'
  vendor/bundle/ruby/1.9.1/gems/unicorn-4.8.2/bin/unicorn_rails:209:in `<top (required)>'
  vendor/bundle/ruby/1.9.1/bin/unicorn_rails:23:in `load'
  vendor/bundle/ruby/1.9.1/bin/unicorn_rails:23:in `<main>'
```

I'm wanting to get the JSON output of the page so that I may improve my CI token grabber: https://github.com/sammcj/getcitoken

**Comment by jvanbaarsen** [comment]
@sammcj You have to fetch the runners via the API. you can do so with the following end-point: https://gitlab.com/gitlab-org/gitlab-ci/blob/master/doc/api/runners.md#retrieve-all-runners
